
experiment:
  name: "stage3"
  version: "1.0"
  seed: 31

data:
  dataset_name: "VOC-2012"
  dataset_path: "/kaggle/input/datasets"
  weak_dataset_path: "husamo/sbd-dataset/weak_dataset"
  train_dataset_path: "gopalbhattrai/pascal-voc-2012-dataset/VOC2012_train_val/VOC2012_train_val"
  test_dataset_path: "gopalbhattrai/pascal-voc-2012-dataset/VOC2012_test/VOC2012_test"
  output_path: "outputs/"

model:
  model_name: ""
  backbone: ""
  correcting_variant: "conv_correction"
  num_classes: 21
  class_labels:
    - background
    - aeroplane
    - bicycle
    - bird
    - boat
    - bottle
    - bus
    - car
    - cat
    - chair
    - cow
    - diningtable
    - dog
    - horse
    - motorbike
    - person
    - pottedplant
    - sheep
    - sofa
    - train
    - tvmonitor

training:
  training_stage: 1
  continue_traning: False
  optimizer: "AdamW"
  batch_size: 8
  grad_acc_steps: 2
  stage1_num_epochs: 650
  stage2_num_epochs: 650
  stage3_num_epochs: 65
  learning_rate: 7e-3
  correcting_lr: 5e-4
  weight_decay: 4e-5
